development:
  cloud_name: idea-portal
  api_key: '369861239759653'
  api_secret: dbT0iB0U_zfm-lwYT0PO3uI_-pM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: idea-portal
  api_key: '369861239759653'
  api_secret: dbT0iB0U_zfm-lwYT0PO3uI_-pM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: idea-portal
  api_key: '369861239759653'
  api_secret: dbT0iB0U_zfm-lwYT0PO3uI_-pM
  enhance_image_tag: true
  static_image_support: false
